### ISSUE TITLE
This entire project is horrible

### ISSUE THREAD

**Issue by pompompurins** [DarkRabbit-0/dbin#8]
I hope you delete your github account before you try to apply for a job

**Comment by DogsAndTwelveKittens** [comment]
Vouch

**Comment by DarkRabbit-0** [comment]
> I hope you delete your github account before you try to apply for a job

I don't understand why u are so interested in my github. U are the owner of skidbin please go manage that. I have no problems getting jobs my work experience is all i need. If u have something to say please pm me about it, don't make useless issues about stupid stuff.
